spring.application.name=Eventify-SpringSecurity

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/eventify
spring.datasource.username=postgres
spring.datasource.password=salmahm
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.com.eventify=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Disable open-in-view ( for production)
spring.jpa.open-in-view=false

# Suppress UserDetailsService warning (we use CustomAuthenticationProvider)
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
